### ISSUE TITLE
make lint fails

### ISSUE THREAD

**Issue by sidhujag** [coinbase/rosetta-bitcoin#40]
I ran make lint on the latest master and saw this:
`node.go:46:14: wrapperFunc: use strings.ReplaceAll method in `strings.Replace(str, "\n", "", -1)` (gocritic)
		message := strings.Replace(str, "\n", "", -1`

**Comment by patrick-ogrady** [comment]
Which version of `golangci-lint` are you using? `master` is currently running `v1.30.0`:

https://github.com/coinbase/rosetta-bitcoin/blob/7e7f67e2e600e5a29dcc6f013a63a9dda30ace1f/.circleci/config.yml#L53

**Comment by sidhujag** [comment]
yea that might be it, I'm on 1.32.2

**Comment by patrick-ogrady** [comment]
Oof we're behind...I'd be happy to review a PR that updates it and fixes any linting issues!
