### ISSUE TITLE
Motivation behind --enable-glibc-back-compat

### ISSUE THREAD

**Issue by sidhujag** [coinbase/rosetta-bitcoin#44]
Hey Patrick,

Why is [--enable-glibc-back-compat ](https://github.com/coinbase/rosetta-bitcoin/blob/master/Dockerfile#L33)set without doing either a static or a depends build? I can see how dependencies needed in core would have issues depending on what versions of glibc they were built with and the core wouldn't have wrapped functions for those at runtime. Usually this flag is set when dependencies are also built so deterministic builds can be built with a lowest common glibc in mind. What is the minimum version you guys must support and why not allow it to be standard bionic install or otherwise just build via depends?

**Comment by patrick-ogrady** [comment]
🤦  I added this when trying to avoid needing to install extra dependencies in the final image but forgot to remove it when I couldn't get it to work:
https://github.com/coinbase/rosetta-bitcoin/blob/07362e928e5e10d5845246a87e0bb761db94c85a/Dockerfile#L72-L74

Happy to review a PR that removes this, @sidhujag !
