### ISSUE TITLE
Rosetta keeps crashing frequently with bitcoin EOF error

### ISSUE THREAD

**Issue by HelloKashif** [coinbase/rosetta-bitcoin#48]
Rosetta keeps crashing around 388k index and 560k tip with different errors like EOF.

Any idea why this is giving EOF?
```

WARN    bitcoind stderr bitcoin/node.go:42      closing logger  {"error": "EOF"}
github.com/coinbase/rosetta-bitcoin/bitcoin.logPipe
        /app/src/bitcoin/node.go:42
github.com/coinbase/rosetta-bitcoin/bitcoin.StartBitcoind.func2
        /app/src/bitcoin/node.go:88
golang.org/x/sync/errgroup.(*Group).Go.func1
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57
2020-11-27T00:06:04.857Z        WARN    pruner  indexer/indexer.go:284  exiting pruner
github.com/coinbase/rosetta-bitcoin/indexer.(*Indexer).Prune
        /app/src/indexer/indexer.go:284
main.startOnlineDependencies.func3
        /app/src/main.go:108
golang.org/x/sync/errgroup.(*Group).Go.func1
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57
2020-11-27T00:06:04.857Z        WARN    bitcoind        bitcoin/node.go:98      sending interrupt to bitcoind
github.com/coinbase/rosetta-bitcoin/bitcoin.StartBitcoind.func3
        /app/src/bitcoin/node.go:98
golang.org/x/sync/errgroup.(*Group).Go.func1
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57
2020-11-27T00:06:03.487Z        WARN    bitcoind        bitcoin/node.go:42      closing logger  {"error": "EOF"}
github.com/coinbase/rosetta-bitcoin/bitcoin.logPipe
        /app/src/bitcoin/node.go:42
github.com/coinbase/rosetta-bitcoin/bitcoin.StartBitcoind.func1
        /app/src/bitcoin/node.go:84
golang.org/x/sync/errgroup.(*Group).Go.func1
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57
```

More info:
we were also calling /network/status while this was running which might have caused this error because the EOF seems like a common error in APIs. However if thats the case then the API crashing the bitcoin node seems very odd

**Comment by sidhujag** [comment]
Let's try on 0.6.2 SDK, just waiting on @patrick-ogrady to update rosetta-bitcoin to v0.6.2 which requires storage module updates. My guess is that he is working on it right now so once he is done lets try it again

**Comment by patrick-ogrady** [comment]
This will slip until tomorrow morning...will close this issue when I merge the update.

**Comment by HelloKashif** [comment]
Good, I'm gonna try the new merged code again. I think this will not occur on the new code.

**Comment by sidhujag** [comment]
> Good, I'm gonna try the new merged code again and report. I think this will not occur on the new code.

you will have to wait until next rosetta-bitcoin release

**Comment by patrick-ogrady** [comment]
I'm releasing one more small improvement to the `storage` model and will update after: https://github.com/coinbase/rosetta-sdk-go/pull/261

This doesn't really have an effect on what `rosetta-bitcoin` does when syncing/serving requests but would require another data migration when released.

**Comment by sidhujag** [comment]
> I'm releasing one more small improvement to the `storage` model and will update after: [coinbase/rosetta-sdk-go#261](https://github.com/coinbase/rosetta-sdk-go/pull/261)
> 
> This doesn't really have an effect on what `rosetta-bitcoin` does when syncing/serving requests but would require another data migration when released. Will still be done today!

Take your time patrick, don't rush. No races here. We will be here to validate when ready.

**Comment by patrick-ogrady** [comment]
Give it a go @HelloKashif and @sidhujag! I'm testing a full sync on my side as well. https://github.com/coinbase/rosetta-bitcoin/releases/tag/v0.0.8

**Comment by sidhujag** [comment]
@patrick-ogrady thanks looks good. With default table/log sizes it syncs up to the offending block and pauses ( i guess database tx size issue was hit ). I went to the increased size I did before https://github.com/syscoin/rosetta-syscoin/commit/3c6a8b91cea8013545e7c7a69376a3bd91cd2f3a

Then it synced passed it, memory was around 8gb before now its around 15.5gb but it synced.

**Comment by patrick-ogrady** [comment]
Do you know what the resident set is when it is synced, @sidhujag? The memory mapping will use a much larger virtual memory allocation than what it actually occupies (the golang GC is super lazy as well).

**Comment by sidhujag** [comment]
> Do you know what the resident set is when it is synced, @sidhujag? The memory mapping will use a much larger virtual memory allocation than what it actually occupies (the golang GC is super lazy as well).

Its a bit over 8GB once synced, stopped started

**Comment by HelloKashif** [comment]
@patrick-ogrady thanks.
Syncing now. It definitely feels faster than before but will have to wait until its around 300k blocks where most of the slow block occurred for me. I'm currently around 230k in indexer and its taking around 5min per 1000 blocks. Memory usage is around 16-19GB

@sidhujag I didn't see the above error in bitcoin so far.

but I did seen this tx skipped log warning (Not really sure if its an error or expected behavior)
<img width="1524" alt="tx skipped" src="https://user-images.githubusercontent.com/9801383/100964397-e124f300-356b-11eb-8f2c-9744972e8144.png">

**Comment by patrick-ogrady** [comment]
>but I did seen this tx skipped log warning (Not really sure if its an error or expected behavior)

This is expected! This is related to this block: https://github.com/coinbase/rosetta-bitcoin/blob/7b5393dca11490da30594c211dc3b716900e4ac0/bitcoin/client.go#L511-L521

If things still aren't fast enough, I know of another optimization to the sync loop (although potentially more invasive) that would add another ~10x.

**Comment by sidhujag** [comment]
> > but I did seen this tx skipped log warning (Not really sure if its an error or expected behavior)
> 
> This is expected! This is related to this block:
> 
> https://github.com/coinbase/rosetta-bitcoin/blob/7b5393dca11490da30594c211dc3b716900e4ac0/bitcoin/client.go#L511-L521
> 
> If things still aren't fast enough, I know of another optimization to the sync loop (although potentially more invasive) that would add another ~10x.

10x improvements are hard to come by heh, I think it makes sense if coverage is good enough and adequate testing is done it seems like a good win.

**Comment by patrick-ogrady** [comment]
> 10x improvements are hard to come by heh, I think it makes sense if coverage is good enough and adequate testing is done it seems like a good win.

More or less involves optimistically storing block data before it is sequenced in `syncer` (could be done concurrently). Right now, we wait to start storing blocks until they are canonicalized (creating a single-threaded bottleneck).

**Comment by HelloKashif** [comment]
More updates around 322k blocks:
Now the indexer takes ~20min per 1000 blocks (Compared to before this is slightly faster I think). 
Peak memory usage was ~32GB (I think the recommendation for rosetta-bitcoin should be increased from 16GB to higher RAM to prevent swap usage)

At this rate it will take about 5 days to fully sync the indexer which I'm okay with. But I'm open to get that 10x boost as well :)

**Comment by patrick-ogrady** [comment]
@HelloKashif @sidhujag : https://github.com/coinbase/rosetta-bitcoin/tree/patrick/encounter-optimization

This thing is irresponsibly fast...past here I'm not sure how to make it any faster haha

**Comment by sidhujag** [comment]
That sounds exciting can't wait to try it out once merged

**Comment by HelloKashif** [comment]
@patrick-ogrady does your branch requires a clean build or can it work with existing data? 
Seems like there might be some changes to storage.

**Comment by patrick-ogrady** [comment]
This will require a new data directory 😢 ... Added an optimized encoder for balance changes that isn't compatible with the previous format (uses 30% of the space + >5x faster).

**Comment by sidhujag** [comment]
> This will require a new data directory 😢 ... Added an optimized encoder for balance changes that isn't compatible with the previous format (uses 30% of the space + >5x faster).

aha you may want to remove the comment about the need to re-sync from the previous release. I think its good to get these going now so its less contentious when theres more platforms using it. Is it ready for merge or still just testing?

**Comment by HelloKashif** [comment]
@patrick-ogrady thanks. I'm testing your branch now.

**Comment by patrick-ogrady** [comment]
I'm closing this after #53. Let me know if you still run into this, @HelloKashif!
